name: Docker Image CI

on:
  # allows to call this workflow from other workflows
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download build files
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.target
      - shell: bash
        run: tree

      - name: Build docker image
        shell: bash
        run: |
          IMAGE=learn/quarkus-reactive-jvm
          TAG=$(date +%Y%m%d-%H%M)
          docker build -f src/main/docker/Dockerfile.jvm -t ${IMAGE}:${TAG} .
          docker tag $IMAGE:$TAG $IMAGE:latest
          docker images $IMAGE
