name: Docker Image CI

on:
  # allows to call this workflow from other workflows
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.target
      - shell: bash
        run: ls -la

    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
