name: Docker Image CI

on:
  # allows to call this workflow from other workflows
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}-jvm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download build files
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.target
      - shell: bash
        run: tree

      - name: Build docker image
        shell: bash
        run: |
          TAG=$(date +%Y%m%d-%H%M)
          docker build -f src/main/docker/Dockerfile.jvm -t ${{ env.IMAGE }}:${TAG} .
          docker tag ${{ env.IMAGE }}:$TAG ${{ env.IMAGE }}:latest
          docker images ${{ env.IMAGE }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
