# This is workflow runs on push
#
name: Push

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
      - name: Use a repo or org secret
        run: echo ${{ secrets.GITHUB_TOKEN }}

  # codeql:
  #   permissions:
  #     actions: read
  #     contents: read
  #     security-events: write
  #   uses: ./.github/workflows/codeql.yml
  #   secrets:
  #     token: ${{ secrets.GITHUB_TOKEN }}

  maven:
    name: '▶️ actions'
    uses: ./.github/workflows/maven.yml
