# This is workflow runs on push
#
name: Push

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  codeql:
    name: '▶️ actions'
    uses: ./.github/workflows/codeql.yml

  maven:
    name: '▶️ actions'
    uses: ./.github/workflows/maven.yml
