# This is workflow runs on PR

name: Pull request

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  maven:
    name: '▶️ actions'
    uses: ./.github/workflows/maven.yml
