# This is workflow runs on PR

name: Pull request

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
      - name: Use a repo or org secret
        run: echo ${{ secrets.GITHUB_TOKEN }}

  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  maven:
    uses: ./.github/workflows/maven.yml
