# This is workflow runs on PR
#
name: Pull request target

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: PRT_${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  codeql:
    name: '▶️ actions'
    uses: ./.github/workflows/codeql.yml

  maven:
    name: '▶️ actions'
    uses: ./.github/workflows/maven.yml
