name: Pull request

on:
#  pull_request_target:
#    types: [opened, synchronize, reopened]

  pull_request:

permissions:
  security-events: write

jobs:
  pmd:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/pmd.yml

  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql.yml

  maven:
    uses: ./.github/workflows/maven.yml

  docker:
    needs: [maven]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-image.yml
