name: Pull request

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  security-events: write

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
  trace:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: tree

  pmd:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/pmd.yml

  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql.yml

  maven:
    uses: ./.github/workflows/maven.yml

  docker:
    needs: [maven]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-image.yml
