name: Push

on:
  # Trigger workflow for pull requests.
  push:
    branches: [main, develop]

  # allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  pmd:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/pmd.yml

  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql.yml

  maven:
    uses: ./.github/workflows/maven.yml

  docker:
    needs: [maven]
    uses: ./.github/workflows/docker-image.yml
